/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DirectoryRouteImport } from './routes/directory'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BrewCompassRouteImport } from './routes/brew-compass'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CafesCafeIdRouteImport } from './routes/cafes.$cafeId'
import { Route as CountryCityRouteImport } from './routes/$country.$city'
import { Route as CountryCityCafeSlugRouteImport } from './routes/$country.$city.$cafeSlug'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryRoute = DirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BrewCompassRoute = BrewCompassRouteImport.update({
  id: '/brew-compass',
  path: '/brew-compass',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CafesCafeIdRoute = CafesCafeIdRouteImport.update({
  id: '/cafes/$cafeId',
  path: '/cafes/$cafeId',
  getParentRoute: () => rootRouteImport,
} as any)
const CountryCityRoute = CountryCityRouteImport.update({
  id: '/$country/$city',
  path: '/$country/$city',
  getParentRoute: () => rootRouteImport,
} as any)
const CountryCityCafeSlugRoute = CountryCityCafeSlugRouteImport.update({
  id: '/$cafeSlug',
  path: '/$cafeSlug',
  getParentRoute: () => CountryCityRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/brew-compass': typeof BrewCompassRoute
  '/contact': typeof ContactRoute
  '/directory': typeof DirectoryRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/$country/$city': typeof CountryCityRouteWithChildren
  '/cafes/$cafeId': typeof CafesCafeIdRoute
  '/$country/$city/$cafeSlug': typeof CountryCityCafeSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/brew-compass': typeof BrewCompassRoute
  '/contact': typeof ContactRoute
  '/directory': typeof DirectoryRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/$country/$city': typeof CountryCityRouteWithChildren
  '/cafes/$cafeId': typeof CafesCafeIdRoute
  '/$country/$city/$cafeSlug': typeof CountryCityCafeSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/brew-compass': typeof BrewCompassRoute
  '/contact': typeof ContactRoute
  '/directory': typeof DirectoryRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/$country/$city': typeof CountryCityRouteWithChildren
  '/cafes/$cafeId': typeof CafesCafeIdRoute
  '/$country/$city/$cafeSlug': typeof CountryCityCafeSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/brew-compass'
    | '/contact'
    | '/directory'
    | '/login'
    | '/signup'
    | '/$country/$city'
    | '/cafes/$cafeId'
    | '/$country/$city/$cafeSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/brew-compass'
    | '/contact'
    | '/directory'
    | '/login'
    | '/signup'
    | '/$country/$city'
    | '/cafes/$cafeId'
    | '/$country/$city/$cafeSlug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/brew-compass'
    | '/contact'
    | '/directory'
    | '/login'
    | '/signup'
    | '/$country/$city'
    | '/cafes/$cafeId'
    | '/$country/$city/$cafeSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  BrewCompassRoute: typeof BrewCompassRoute
  ContactRoute: typeof ContactRoute
  DirectoryRoute: typeof DirectoryRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  CountryCityRoute: typeof CountryCityRouteWithChildren
  CafesCafeIdRoute: typeof CafesCafeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory': {
      id: '/directory'
      path: '/directory'
      fullPath: '/directory'
      preLoaderRoute: typeof DirectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brew-compass': {
      id: '/brew-compass'
      path: '/brew-compass'
      fullPath: '/brew-compass'
      preLoaderRoute: typeof BrewCompassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cafes/$cafeId': {
      id: '/cafes/$cafeId'
      path: '/cafes/$cafeId'
      fullPath: '/cafes/$cafeId'
      preLoaderRoute: typeof CafesCafeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$country/$city': {
      id: '/$country/$city'
      path: '/$country/$city'
      fullPath: '/$country/$city'
      preLoaderRoute: typeof CountryCityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$country/$city/$cafeSlug': {
      id: '/$country/$city/$cafeSlug'
      path: '/$cafeSlug'
      fullPath: '/$country/$city/$cafeSlug'
      preLoaderRoute: typeof CountryCityCafeSlugRouteImport
      parentRoute: typeof CountryCityRoute
    }
  }
}

interface CountryCityRouteChildren {
  CountryCityCafeSlugRoute: typeof CountryCityCafeSlugRoute
}

const CountryCityRouteChildren: CountryCityRouteChildren = {
  CountryCityCafeSlugRoute: CountryCityCafeSlugRoute,
}

const CountryCityRouteWithChildren = CountryCityRoute._addFileChildren(
  CountryCityRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  BrewCompassRoute: BrewCompassRoute,
  ContactRoute: ContactRoute,
  DirectoryRoute: DirectoryRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  CountryCityRoute: CountryCityRouteWithChildren,
  CafesCafeIdRoute: CafesCafeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
