/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DirectoryRouteImport } from './routes/directory'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BrewCompassRouteImport } from './routes/brew-compass'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BrewCompassIndexRouteImport } from './routes/brew-compass/index'
import { Route as CafesCafeIdRouteImport } from './routes/cafes.$cafeId'
import { Route as BrewCompassMilkTypesRouteImport } from './routes/brew-compass/milk-types'
import { Route as BrewCompassMenuDecoderRouteImport } from './routes/brew-compass/menu-decoder'
import { Route as BrewCompassGlobalSpecialtiesRouteImport } from './routes/brew-compass/global-specialties'
import { Route as BrewCompassConnoisseurRouteImport } from './routes/brew-compass/connoisseur'
import { Route as BrewCompassCoffeeAtlasRouteImport } from './routes/brew-compass/coffee-atlas'
import { Route as BrewCompassChilledBarRouteImport } from './routes/brew-compass/chilled-bar'
import { Route as BrewCompassBlackCoffeeRouteImport } from './routes/brew-compass/black-coffee'
import { Route as BrewCompassBeanRoastSpectrumRouteImport } from './routes/brew-compass/bean-roast-spectrum'
import { Route as CountryCityRouteImport } from './routes/$country.$city'
import { Route as CountryCityCafeSlugRouteImport } from './routes/$country.$city.$cafeSlug'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryRoute = DirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BrewCompassRoute = BrewCompassRouteImport.update({
  id: '/brew-compass',
  path: '/brew-compass',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrewCompassIndexRoute = BrewCompassIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BrewCompassRoute,
} as any)
const CafesCafeIdRoute = CafesCafeIdRouteImport.update({
  id: '/cafes/$cafeId',
  path: '/cafes/$cafeId',
  getParentRoute: () => rootRouteImport,
} as any)
const BrewCompassMilkTypesRoute = BrewCompassMilkTypesRouteImport.update({
  id: '/milk-types',
  path: '/milk-types',
  getParentRoute: () => BrewCompassRoute,
} as any)
const BrewCompassMenuDecoderRoute = BrewCompassMenuDecoderRouteImport.update({
  id: '/menu-decoder',
  path: '/menu-decoder',
  getParentRoute: () => BrewCompassRoute,
} as any)
const BrewCompassGlobalSpecialtiesRoute =
  BrewCompassGlobalSpecialtiesRouteImport.update({
    id: '/global-specialties',
    path: '/global-specialties',
    getParentRoute: () => BrewCompassRoute,
  } as any)
const BrewCompassConnoisseurRoute = BrewCompassConnoisseurRouteImport.update({
  id: '/connoisseur',
  path: '/connoisseur',
  getParentRoute: () => BrewCompassRoute,
} as any)
const BrewCompassCoffeeAtlasRoute = BrewCompassCoffeeAtlasRouteImport.update({
  id: '/coffee-atlas',
  path: '/coffee-atlas',
  getParentRoute: () => BrewCompassRoute,
} as any)
const BrewCompassChilledBarRoute = BrewCompassChilledBarRouteImport.update({
  id: '/chilled-bar',
  path: '/chilled-bar',
  getParentRoute: () => BrewCompassRoute,
} as any)
const BrewCompassBlackCoffeeRoute = BrewCompassBlackCoffeeRouteImport.update({
  id: '/black-coffee',
  path: '/black-coffee',
  getParentRoute: () => BrewCompassRoute,
} as any)
const BrewCompassBeanRoastSpectrumRoute =
  BrewCompassBeanRoastSpectrumRouteImport.update({
    id: '/bean-roast-spectrum',
    path: '/bean-roast-spectrum',
    getParentRoute: () => BrewCompassRoute,
  } as any)
const CountryCityRoute = CountryCityRouteImport.update({
  id: '/$country/$city',
  path: '/$country/$city',
  getParentRoute: () => rootRouteImport,
} as any)
const CountryCityCafeSlugRoute = CountryCityCafeSlugRouteImport.update({
  id: '/$cafeSlug',
  path: '/$cafeSlug',
  getParentRoute: () => CountryCityRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/brew-compass': typeof BrewCompassRouteWithChildren
  '/contact': typeof ContactRoute
  '/directory': typeof DirectoryRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/$country/$city': typeof CountryCityRouteWithChildren
  '/brew-compass/bean-roast-spectrum': typeof BrewCompassBeanRoastSpectrumRoute
  '/brew-compass/black-coffee': typeof BrewCompassBlackCoffeeRoute
  '/brew-compass/chilled-bar': typeof BrewCompassChilledBarRoute
  '/brew-compass/coffee-atlas': typeof BrewCompassCoffeeAtlasRoute
  '/brew-compass/connoisseur': typeof BrewCompassConnoisseurRoute
  '/brew-compass/global-specialties': typeof BrewCompassGlobalSpecialtiesRoute
  '/brew-compass/menu-decoder': typeof BrewCompassMenuDecoderRoute
  '/brew-compass/milk-types': typeof BrewCompassMilkTypesRoute
  '/cafes/$cafeId': typeof CafesCafeIdRoute
  '/brew-compass/': typeof BrewCompassIndexRoute
  '/$country/$city/$cafeSlug': typeof CountryCityCafeSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/directory': typeof DirectoryRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/$country/$city': typeof CountryCityRouteWithChildren
  '/brew-compass/bean-roast-spectrum': typeof BrewCompassBeanRoastSpectrumRoute
  '/brew-compass/black-coffee': typeof BrewCompassBlackCoffeeRoute
  '/brew-compass/chilled-bar': typeof BrewCompassChilledBarRoute
  '/brew-compass/coffee-atlas': typeof BrewCompassCoffeeAtlasRoute
  '/brew-compass/connoisseur': typeof BrewCompassConnoisseurRoute
  '/brew-compass/global-specialties': typeof BrewCompassGlobalSpecialtiesRoute
  '/brew-compass/menu-decoder': typeof BrewCompassMenuDecoderRoute
  '/brew-compass/milk-types': typeof BrewCompassMilkTypesRoute
  '/cafes/$cafeId': typeof CafesCafeIdRoute
  '/brew-compass': typeof BrewCompassIndexRoute
  '/$country/$city/$cafeSlug': typeof CountryCityCafeSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/brew-compass': typeof BrewCompassRouteWithChildren
  '/contact': typeof ContactRoute
  '/directory': typeof DirectoryRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/$country/$city': typeof CountryCityRouteWithChildren
  '/brew-compass/bean-roast-spectrum': typeof BrewCompassBeanRoastSpectrumRoute
  '/brew-compass/black-coffee': typeof BrewCompassBlackCoffeeRoute
  '/brew-compass/chilled-bar': typeof BrewCompassChilledBarRoute
  '/brew-compass/coffee-atlas': typeof BrewCompassCoffeeAtlasRoute
  '/brew-compass/connoisseur': typeof BrewCompassConnoisseurRoute
  '/brew-compass/global-specialties': typeof BrewCompassGlobalSpecialtiesRoute
  '/brew-compass/menu-decoder': typeof BrewCompassMenuDecoderRoute
  '/brew-compass/milk-types': typeof BrewCompassMilkTypesRoute
  '/cafes/$cafeId': typeof CafesCafeIdRoute
  '/brew-compass/': typeof BrewCompassIndexRoute
  '/$country/$city/$cafeSlug': typeof CountryCityCafeSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/brew-compass'
    | '/contact'
    | '/directory'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/$country/$city'
    | '/brew-compass/bean-roast-spectrum'
    | '/brew-compass/black-coffee'
    | '/brew-compass/chilled-bar'
    | '/brew-compass/coffee-atlas'
    | '/brew-compass/connoisseur'
    | '/brew-compass/global-specialties'
    | '/brew-compass/menu-decoder'
    | '/brew-compass/milk-types'
    | '/cafes/$cafeId'
    | '/brew-compass/'
    | '/$country/$city/$cafeSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/directory'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/$country/$city'
    | '/brew-compass/bean-roast-spectrum'
    | '/brew-compass/black-coffee'
    | '/brew-compass/chilled-bar'
    | '/brew-compass/coffee-atlas'
    | '/brew-compass/connoisseur'
    | '/brew-compass/global-specialties'
    | '/brew-compass/menu-decoder'
    | '/brew-compass/milk-types'
    | '/cafes/$cafeId'
    | '/brew-compass'
    | '/$country/$city/$cafeSlug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/brew-compass'
    | '/contact'
    | '/directory'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/$country/$city'
    | '/brew-compass/bean-roast-spectrum'
    | '/brew-compass/black-coffee'
    | '/brew-compass/chilled-bar'
    | '/brew-compass/coffee-atlas'
    | '/brew-compass/connoisseur'
    | '/brew-compass/global-specialties'
    | '/brew-compass/menu-decoder'
    | '/brew-compass/milk-types'
    | '/cafes/$cafeId'
    | '/brew-compass/'
    | '/$country/$city/$cafeSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  BrewCompassRoute: typeof BrewCompassRouteWithChildren
  ContactRoute: typeof ContactRoute
  DirectoryRoute: typeof DirectoryRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  CountryCityRoute: typeof CountryCityRouteWithChildren
  CafesCafeIdRoute: typeof CafesCafeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory': {
      id: '/directory'
      path: '/directory'
      fullPath: '/directory'
      preLoaderRoute: typeof DirectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brew-compass': {
      id: '/brew-compass'
      path: '/brew-compass'
      fullPath: '/brew-compass'
      preLoaderRoute: typeof BrewCompassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brew-compass/': {
      id: '/brew-compass/'
      path: '/'
      fullPath: '/brew-compass/'
      preLoaderRoute: typeof BrewCompassIndexRouteImport
      parentRoute: typeof BrewCompassRoute
    }
    '/cafes/$cafeId': {
      id: '/cafes/$cafeId'
      path: '/cafes/$cafeId'
      fullPath: '/cafes/$cafeId'
      preLoaderRoute: typeof CafesCafeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brew-compass/milk-types': {
      id: '/brew-compass/milk-types'
      path: '/milk-types'
      fullPath: '/brew-compass/milk-types'
      preLoaderRoute: typeof BrewCompassMilkTypesRouteImport
      parentRoute: typeof BrewCompassRoute
    }
    '/brew-compass/menu-decoder': {
      id: '/brew-compass/menu-decoder'
      path: '/menu-decoder'
      fullPath: '/brew-compass/menu-decoder'
      preLoaderRoute: typeof BrewCompassMenuDecoderRouteImport
      parentRoute: typeof BrewCompassRoute
    }
    '/brew-compass/global-specialties': {
      id: '/brew-compass/global-specialties'
      path: '/global-specialties'
      fullPath: '/brew-compass/global-specialties'
      preLoaderRoute: typeof BrewCompassGlobalSpecialtiesRouteImport
      parentRoute: typeof BrewCompassRoute
    }
    '/brew-compass/connoisseur': {
      id: '/brew-compass/connoisseur'
      path: '/connoisseur'
      fullPath: '/brew-compass/connoisseur'
      preLoaderRoute: typeof BrewCompassConnoisseurRouteImport
      parentRoute: typeof BrewCompassRoute
    }
    '/brew-compass/coffee-atlas': {
      id: '/brew-compass/coffee-atlas'
      path: '/coffee-atlas'
      fullPath: '/brew-compass/coffee-atlas'
      preLoaderRoute: typeof BrewCompassCoffeeAtlasRouteImport
      parentRoute: typeof BrewCompassRoute
    }
    '/brew-compass/chilled-bar': {
      id: '/brew-compass/chilled-bar'
      path: '/chilled-bar'
      fullPath: '/brew-compass/chilled-bar'
      preLoaderRoute: typeof BrewCompassChilledBarRouteImport
      parentRoute: typeof BrewCompassRoute
    }
    '/brew-compass/black-coffee': {
      id: '/brew-compass/black-coffee'
      path: '/black-coffee'
      fullPath: '/brew-compass/black-coffee'
      preLoaderRoute: typeof BrewCompassBlackCoffeeRouteImport
      parentRoute: typeof BrewCompassRoute
    }
    '/brew-compass/bean-roast-spectrum': {
      id: '/brew-compass/bean-roast-spectrum'
      path: '/bean-roast-spectrum'
      fullPath: '/brew-compass/bean-roast-spectrum'
      preLoaderRoute: typeof BrewCompassBeanRoastSpectrumRouteImport
      parentRoute: typeof BrewCompassRoute
    }
    '/$country/$city': {
      id: '/$country/$city'
      path: '/$country/$city'
      fullPath: '/$country/$city'
      preLoaderRoute: typeof CountryCityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$country/$city/$cafeSlug': {
      id: '/$country/$city/$cafeSlug'
      path: '/$cafeSlug'
      fullPath: '/$country/$city/$cafeSlug'
      preLoaderRoute: typeof CountryCityCafeSlugRouteImport
      parentRoute: typeof CountryCityRoute
    }
  }
}

interface BrewCompassRouteChildren {
  BrewCompassBeanRoastSpectrumRoute: typeof BrewCompassBeanRoastSpectrumRoute
  BrewCompassBlackCoffeeRoute: typeof BrewCompassBlackCoffeeRoute
  BrewCompassChilledBarRoute: typeof BrewCompassChilledBarRoute
  BrewCompassCoffeeAtlasRoute: typeof BrewCompassCoffeeAtlasRoute
  BrewCompassConnoisseurRoute: typeof BrewCompassConnoisseurRoute
  BrewCompassGlobalSpecialtiesRoute: typeof BrewCompassGlobalSpecialtiesRoute
  BrewCompassMenuDecoderRoute: typeof BrewCompassMenuDecoderRoute
  BrewCompassMilkTypesRoute: typeof BrewCompassMilkTypesRoute
  BrewCompassIndexRoute: typeof BrewCompassIndexRoute
}

const BrewCompassRouteChildren: BrewCompassRouteChildren = {
  BrewCompassBeanRoastSpectrumRoute: BrewCompassBeanRoastSpectrumRoute,
  BrewCompassBlackCoffeeRoute: BrewCompassBlackCoffeeRoute,
  BrewCompassChilledBarRoute: BrewCompassChilledBarRoute,
  BrewCompassCoffeeAtlasRoute: BrewCompassCoffeeAtlasRoute,
  BrewCompassConnoisseurRoute: BrewCompassConnoisseurRoute,
  BrewCompassGlobalSpecialtiesRoute: BrewCompassGlobalSpecialtiesRoute,
  BrewCompassMenuDecoderRoute: BrewCompassMenuDecoderRoute,
  BrewCompassMilkTypesRoute: BrewCompassMilkTypesRoute,
  BrewCompassIndexRoute: BrewCompassIndexRoute,
}

const BrewCompassRouteWithChildren = BrewCompassRoute._addFileChildren(
  BrewCompassRouteChildren,
)

interface CountryCityRouteChildren {
  CountryCityCafeSlugRoute: typeof CountryCityCafeSlugRoute
}

const CountryCityRouteChildren: CountryCityRouteChildren = {
  CountryCityCafeSlugRoute: CountryCityCafeSlugRoute,
}

const CountryCityRouteWithChildren = CountryCityRoute._addFileChildren(
  CountryCityRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  BrewCompassRoute: BrewCompassRouteWithChildren,
  ContactRoute: ContactRoute,
  DirectoryRoute: DirectoryRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  CountryCityRoute: CountryCityRouteWithChildren,
  CafesCafeIdRoute: CafesCafeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
